// Consumer-side compatibility of the packed package: JavaScript (ESM, CommonJS) and
// TypeScript (node16 module / commonjs, bundler, node10). Needs `dist/` — built by `pretest`.
// Also checks that the generated src/version.ts matches package.json.
import { test, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, writeFileSync, copyFileSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const fixtures = join(root, 'tests', 'compat', 'fixtures')
const tsc = join(root, 'node_modules', 'typescript', 'bin', 'tsc')
const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm'

/** Runs a command and returns its stdout, throws with the full output on failure */
function run(cmd, args, cwd) {
  const r = spawnSync(cmd, args, { cwd, encoding: 'utf8', shell: process.platform === 'win32' })
  if (r.error) {
    throw new Error(`cannot run ${cmd} (${r.error.message}): the compatibility tests need npm on the PATH`)
  }
  if (r.status !== 0) {
    throw new Error(`${cmd} ${args.join(' ')} failed (status ${r.status})\n${r.stdout}\n${r.stderr}`)
  }
  return r.stdout
}

/** Runs a script with node and parses the JSON object it prints on its last line */
function runNode(script, cwd) {
  const lines = run(process.execPath, [script], cwd).trim().split('\n')
  return JSON.parse(lines[lines.length - 1])
}

// ─── Throwaway consumer project: `npm pack` → `npm install <tgz>` ─────────────

let consumer

before(() => {
  consumer = mkdtempSync(join(tmpdir(), 'bitgen-sdk-compat-'))
  // --no-dry-run: when the suite runs from `npm publish --dry-run` (prepublishOnly), npm exports its dry-run
  // flag to nested npm commands, which would then write nothing
  const packed = JSON.parse(run(npm, ['pack', '--json', '--no-dry-run', '--pack-destination', consumer], root))
  // npm <= 11 prints an array, npm 12 an object keyed by package name
  const { filename } = Array.isArray(packed) ? packed[0] : Object.values(packed)[0]
  writeFileSync(join(consumer, 'package.json'), JSON.stringify({ name: 'consumer', private: true }))
  // Local tarball, no dependency: works offline
  run(npm, ['install', '--no-dry-run', '--offline', '--no-audit', '--no-fund', '--no-package-lock', '--ignore-scripts', join(consumer, filename)], consumer)
})

after(() => {
  if (consumer) {
    rmSync(consumer, { recursive: true, force: true })
  }
})

// ─── Version ──────────────────────────────────────────────────────────────────

test('src/version.ts (generated by scripts/prebuild.js) matches package.json', () => {
  const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  assert.equal(readFileSync(join(root, 'src', 'version.ts'), 'utf8'), `// Generated by scripts/prebuild.js from package.json — do not edit\nexport const VERSION = ${JSON.stringify(version)}\n`)
})

// ─── JavaScript ───────────────────────────────────────────────────────────────

const JS_BODY = `
const client = new BitgenClient({ scope: 'YOUR_SCOPE_UUID', apiKey: 'YOUR_API_KEY', env: Env.PRODUCTION })
const err = new BitgenError(400, { error: true, message: 'invalid_amount', code: 400 })
console.log(JSON.stringify({
  client: client instanceof BitgenClient,
  asset: typeof client.asset.get === 'function',
  customer: typeof client.customer.create === 'function',
  bank: typeof client.bank.withdraw === 'function',
  custody: typeof client.custody.withdraw === 'function',
  trading: typeof client.trading.buy === 'function',
  transaction: typeof client.transaction.get === 'function',
  core: typeof client.core.list === 'function',
  staking: typeof client.staking.stake === 'function',
  webhooks: typeof client.webhooks.verify === 'function',
  apikeys: typeof client.apikeys.logs === 'function',
  error: err instanceof BitgenError && err instanceof Error,
  name: err.name, status: err.status, code: err.code, message: err.message,
  Env, Asset,
  frozen: Object.isFrozen(Env) && Object.isFrozen(Asset),
  constants: [CoreType.STAKING, TradingDirection.BUY, Locale.FR, Object.keys(WebhookEventName).length, Object.isFrozen(OrderState), Object.values(AssetState)],
}))
`
const JS_EXPECTED = {
  client: true,
  asset: true,
  customer: true,
  bank: true,
  custody: true,
  trading: true,
  transaction: true,
  core: true,
  staking: true,
  webhooks: true,
  apikeys: true,
  error: true,
  name: 'BitgenError',
  status: 400,
  code: 'invalid_amount',
  message: '[400] invalid_amount',
  Env: { PRODUCTION: 'production', SANDBOX: 'sandbox', STAGING: 'staging', LOCALHOST: 'localhost' },
  Asset: { BTC: 'btc', ETH: 'eth', USDC: 'usdc', XRP: 'xrp', SOL: 'sol' },
  frozen: true,
  constants: ['STAKING', 'buy', 'FR', 33, true, ['AVAILABLE', 'UNAVAILABLE', 'ARCHIVED', 'HIDDEN']],
}

test('JavaScript ESM consumer (import from .mjs)', () => {
  writeFileSync(join(consumer, 'esm.mjs'), `import { BitgenClient, BitgenError, Env, Asset, CoreType, TradingDirection, Locale, WebhookEventName, OrderState, AssetState } from '@bitgen/sdk'\n${JS_BODY}`)
  assert.deepEqual(runNode('esm.mjs', consumer), JS_EXPECTED)
})

test('JavaScript CommonJS consumer (require from .cjs)', () => {
  writeFileSync(join(consumer, 'cjs.cjs'), `const { BitgenClient, BitgenError, Env, Asset, CoreType, TradingDirection, Locale, WebhookEventName, OrderState, AssetState } = require('@bitgen/sdk')\n${JS_BODY}`)
  assert.deepEqual(runNode('cjs.cjs', consumer), JS_EXPECTED)
})

// ─── TypeScript ───────────────────────────────────────────────────────────────

const TS_BASE = { target: 'es2020', lib: ['es2020'], types: [], strict: true, skipLibCheck: false }
const TS_PROJECTS = {
  'node16 / module': { type: 'module', options: { module: 'node16', moduleResolution: 'node16', outDir: 'dist' }, run: true },
  'node16 / commonjs': { type: 'commonjs', options: { module: 'node16', moduleResolution: 'node16', outDir: 'dist' }, run: true },
  'bundler': { type: 'module', options: { module: 'esnext', moduleResolution: 'bundler', noEmit: true } },
  'node10': { type: 'commonjs', options: { module: 'commonjs', moduleResolution: 'node10', noEmit: true } },
}
const TS_EXPECTED = {
  client: true, error: true, status: 400, code: 'invalid_amount', env: 'staging',
  eth: 'eth', anyAsset: 'sol', state: 'AVAILABLE', price: 1, count: 2, refs: 5, customerState: 'CREATED', locale: 'FR', narrowed: null, anyAmount: 50,
  bankHistories: [0, 5], bankOp: 'DEPOSIT', walletHistory: true, portfolioUuid: null, orderState: 'FILLED',
  txAlerts: [true, 'KYT'], coreAssets: ['ETH', null], staking: ['p', 'something-new', 1],
  webhooks: ['sent', 'something.new', null], apikeys: [null, 'Hub', 200],
  constants: ['STAKING', 'RAMP', 'buy', 'custody.sent', 'something.new', 17, 4, true, 33, 'B2B', true, true, 'ARCHIVED'],
}

for (const [name, project] of Object.entries(TS_PROJECTS)) {
  test(`TypeScript consumer (${name})`, () => {
    const dir = join(consumer, `ts-${name.replace(/\W+/g, '-')}`)
    mkdirSync(dir)
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ type: project.type }))
    writeFileSync(join(dir, 'tsconfig.json'), JSON.stringify({ compilerOptions: { ...TS_BASE, ...project.options }, include: ['main.ts'] }))
    copyFileSync(join(fixtures, 'main.ts'), join(dir, 'main.ts'))

    run(process.execPath, [tsc, '-p', 'tsconfig.json'], dir)
    if (project.run) {
      assert.deepEqual(runNode(join('dist', 'main.js'), dir), TS_EXPECTED)
    }
  })
}
