// Runs before `npm run build` (npm `prebuild` hook) and on `npm version` (npm `version` hook), from the package root:
// - cleans dist/ so a deleted source never leaves a stale file in the published package
// - regenerates src/version.ts from package.json, the only source of the version (User-Agent header);
//   the file is committed, and only rewritten when its content changes
import { readFileSync, rmSync, writeFileSync } from 'node:fs'

const { version } = JSON.parse(readFileSync('package.json', 'utf8'))
if (typeof version !== 'string' || version === '') {
  throw new Error('package.json: "version" must be a non-empty string')
}

rmSync('dist', { recursive: true, force: true })

const file = 'src/version.ts'
const content = `// Generated by scripts/prebuild.js from package.json — do not edit\nexport const VERSION = ${JSON.stringify(version)}\n`
let current = ''
try {
  current = readFileSync(file, 'utf8')
} catch {
  // first generation
}
if (current !== content) {
  writeFileSync(file, content)
}
