import { Env, Asset as AssetCodes } from './constants.js'
import type { Asset as AssetType } from './types/index.js'

export { BitgenClient } from './client.js'
export { BitgenError } from './error.js'
export { Env }

// Enumerated values — each name is both the frozen object of constants and the type of its values (`CoreType.STAKING`)
export {
  ApikeyState,
  AssetState,
  BankDirection,
  CoreState,
  CoreType,
  CustomerState,
  IdentityMode,
  IdentityState,
  Locale,
  OrderSide,
  OrderState,
  OrganizationCategory,
  StakingMovementKind,
  StakingMovementState,
  StakingPositionState,
  SubscriberState,
  TradingDirection,
  TransactionDirection,
  TransactionSource,
  TransactionState,
  WalletState,
  WalletType,
  WebhookEventName,
} from './constants.js'

/** Asset ISO codes (`Asset.ETH`) — `Asset` is also the type of an asset returned by `client.asset` */
export const Asset = AssetCodes
export type Asset = AssetType

export type {
  BitgenConfig,
  BitgenEnv,
  UserRef,
  Amount,
  PageParams,
  Page,
  BitgenErrorBody,
  History,
  Created,
  AssetRef,
  AssetInput,
  UserSummary,
  OrganizationHub,
  OrganizationSummary,
  AssetTicker,
  AssetFees,
  AssetNetwork,
  AssetNetworkType,
  KycIdentity,
  KybIdentity,
  Identity,
  CustomerAccount,
  CustomerClient,
  CustomerSetup,
  CollaboratorLink,
  ManagerLink,
  CustomerAlert,
  CustomerBusiness,
  Customer,
  AccountAddress,
  Account,
  CreateCustomerParams,
  CustomerListParams,
  UpdateCustomerParams,
  BankAccount,
  BankOperation,
  BankOperationsParams,
  BankWithdrawParams,
  BankCreditParams,
  Wallet,
  CustodyPortfolio,
  TravelRule,
  CustodyWithdrawParams,
  OrderUser,
  OrderOrganization,
  Order,
  TradingOrderParams,
  TradingListParams,
  TransactionAlert,
  Transaction,
  TransactionListParams,
  CoreConfigField,
  Core,
  CoreListParams,
  CoreRef,
  StakingPosition,
  StakingMovement,
  StakingOperation,
  StakingPortfolio,
  StakeParams,
  StakingListParams,
  StakingAmountParams,
  WebhookType,
  Subscriber,
  WebhookSubscriptions,
  DeliveryLog,
  WebhookEvent,
  VerifyInput,
  Apikey,
  ApikeyLog,
  ApikeyListParams,
} from './types/index.js'
